# ------------------------------------------------------------------------------
# Example Config file for calibration-utility
# 
#   This file follows yaml formatting with keys as described below
#
# ------------------------------------------------------------------------------


# --- input-data-source [STRING]------------------------------------------------
# Input data source describes original source of data
# Valid Values are:
#   digital-globe - data supplied with this key has a directory structure that
#     matches the format of data as downloaded from digital globe.
#     With digital globe data rpc information is used in orthorectification
# 
# other data sources are not supported, this key was mostly included 
# to help future proof the program.
# ------------------------------------------------------------------------------
input-data-source: digital-globe

# --- input-data-directory [PATH]-----------------------------------------------
# Path to root of input data
# ------------------------------------------------------------------------------
input-directory: data/raw/

# --- input-data-directory [PATH]-----------------------------------------------
# Path (relative to `input-directory`)  with wildcard that defines any 
# subdirectories that contain data.
# ------------------------------------------------------------------------------
input-sub-dir-format: iceroad_*

# --- ignore-list [PATH] -------------------------------------------------------
# Path to a text file containing a list input images contained in 
# input-directory into to skip during processing. One per line.
# ------------------------------------------------------------------------------
ignore-list: ignore-list-example.txt


# OUTPUTS ----------------------------------------------------------------------

# --- orthorectified-directory [PATH]-------------------------------------------
# Path to save output files
# ------------------------------------------------------------------------------
output-directory: data/reflectance-data/

# --- calc-reflectance [BOOL]---------------------------------------------------
# If True top of atmosphere reflectance is calculated and saved
# If False top of atmosphere reflectance is NOT calculated and the resulting
#   Data saved is the absolutely radiometric calibrated data
# ------------------------------------------------------------------------------
calc-reflectance: True

# --- report-file [PATH]--------------------------------------------------------
# Path to save a report csv file that maps the input files to the output files
# ------------------------------------------------------------------------------
report-file: calibration-report.csv
